ALGORITHMS = {
    "Bubble Sort": {"function": "bubble_sort", "Best": "O(n)", "Average": "O(n²)", "Worst": "O(n²)", "Space": "O(1)", "Stable": "Yes"},
    "Insertion Sort": {"function": "insertion_sort", "Best": "O(n)", "Average": "O(n²)", "Worst": "O(n²)", "Space": "O(1)", "Stable": "Yes"},
    "Selection Sort": {"function": "selection_sort", "Best": "O(n²)", "Average": "O(n²)", "Worst": "O(n²)", "Space": "O(1)", "Stable": "No"},
    "Quick Sort": {"function": "quick_sort", "Best": "O(n log n)", "Average": "O(n log n)", "Worst": "O(n²)", "Space": "O(log n)", "Stable": "No"},
    "Merge Sort": {"function": "merge_sort", "Best": "O(n log n)", "Average": "O(n log n)", "Worst": "O(n log n)", "Space": "O(n)", "Stable": "Yes"},
    "Heap Sort": {"function": "heap_sort", "Best": "O(n log n)", "Average": "O(n log n)", "Worst": "O(n log n)", "Space": "O(1)", "Stable": "No"},
    "Shell Sort": {"function": "shell_sort", "Best": "O(n log n)", "Average": "O(n log² n)", "Worst": "O(n²)", "Space": "O(1)", "Stable": "No"},
    "Tim Sort": {"function": "tim_sort", "Best": "O(n)", "Average": "O(n log n)", "Worst": "O(n log n)", "Space": "O(n)", "Stable": "Yes"},
    "Counting Sort": {"function": "counting_sort", "Best": "O(n + k)", "Average": "O(n + k)", "Worst": "O(n + k)", "Space": "O(k)", "Stable": "Yes"},
    "Radix Sort": {"function": "radix_sort", "Best": "O(nk)", "Average": "O(nk)", "Worst": "O(nk)", "Space": "O(n + k)", "Stable": "Yes"},
    "Bucket Sort": {"function": "bucket_sort", "Best": "O(n + k)", "Average": "O(n + k)", "Worst": "O(n²)", "Space": "O(n)", "Stable": "Yes"},
    "Cocktail Sort": {"function": "cocktail_sort", "Best": "O(n)", "Average": "O(n²)", "Worst": "O(n²)", "Space": "O(1)", "Stable": "Yes"},
    "Tree Sort": {"function": "tree_sort", "Best": "O(n log n)", "Average": "O(n log n)", "Worst": "O(n²)", "Space": "O(n)", "Stable": "No"},
    "Gnome Sort": {"function": "gnome_sort","Best": "O(n)","Average": "O(n²)","Worst": "O(n²)","Space": "O(1)","Stable": "Yes"},
    "Bitonic Sort": {"function": "bitonic_sort","Best": "O(log² n)","Average": "O(log² n)","Worst": "O(log² n)","Space": "O(n)","Stable": "No"},
    "Cycle Sort": {"function": "cycle_sort","Best": "O(n²)","Average": "O(n²)","Worst": "O(n²)","Space": "O(1)","Stable": "No"},
    "Odd-Even Sort": {"function": "odd_even_sort","Best": "O(n)","Average": "O(n²)","Worst": "O(n²)","Space": "O(1)","Stable": "Yes"},
    "Comb Sort": {"function": "comb_sort","Best": "O(n log n)","Average": "O(n²)","Worst": "O(n²)","Space": "O(1)","Stable": "No"},
    "Stalin Sort": {"function": "stalin_sort","Best": "O(n)","Average": "O(n)","Worst": "O(n)","Space": "O(n)","Stable": "No"},
    "Gravity Sort": {"function": "gravity_sort","Best": "O(n + m)","Average": "O(n + m)","Worst": "O(n + m)","Space": "O(n * m)","Stable": "Yes"},
}